media:
  label: Images
  input: images
  output: /images
  extensions: [ png, webp, jpg ]

content:
  - name: homepage
    label: Home Page
    type: file
    path: src/_data/frontpage.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: subtitle, label: Subtitle, type: string }